categories = {
    'Court de tennis': 'Tennis',
    'Terrain de football': 'FootBall',
    'Bassin sportif de natation	': 'Piscine',
    'Terrain de basket-ball	': 'BasketBall'
}

tryd = {
    'Court de tennis' : 'Tennis', 
    'Terrain de basket-ball': 'BasketBall',
    'Bassin sportif de natation': 'Piscine', 
    'Salle de gymnastique sportive': '',
    "Structure Artificielle d'Escalade": 'Escalade',
    'Terrain de rugby': '',
    "Pas de tir à l'arc": '', 
    'Salle multisports (gymnase)': '',
    'Boucle de randonnée': '', 
    "Site de blocs d'escalade": 'Escalade',
    'Plateau EPS/Multisports/city-stades': '',
    'Terrain de boules': '',
    'Carrière': '', 
    'Carrière de dressage/rond de longe': '',
    'Terrain de football': 'FootBall',
    'Salles polyvalentes / des fêtes / non spécialisées': '',
    'Salle de tennis de table': '', 
    "Piste d'athlétisme isolée": '',
    'Stade d’athlétisme': '',
    'Salle de cours collectifs': '',
    "Salle d'escrime": '',
    'Piste de kart': '',
    'Salle de musculation/cardiotraining': '',
    'Terrain de pétanque': '',
    "Dojo / Salle d'arts martiaux": '',
    'Parcours sportif/santé': '',
    'Stade de ski nautique': '',
    'Salle de danse': '',
    'Parcours fixe de course d’orientation': '',
    "Site d'escalade en falaise": 'Escalade',
    'Skate park': '',
    'Piste de bicross': '',
    'Manège': '', 
    'Terrain de handball': '',
    'Aire de saut': '', 
    'Mur de tennis': '',
    'Salle de boxe': '', 
    'Pas de tir à la cible': '',
    'Terrain de volley-ball': '',
    'Parcours de cross': '', 
    'Bassin ludique de natation': '',
    'Bassin mixte de natation': '', 
    'Terrain de soccer': '', 
    'Salle de basket': 'BasketBall',
    "Site d'activités aquatiques et nautiques": '',
    'Aire de décollage': '',
    'Terrain mixte': '', 
    'Salle de billard': '',
    "Bassin d'exercices aquatiques": '',
    'Piste de course sur le plat': '',
    'Aire de lancer': '', 
    'Salle de lutte': '',
    'Salle ou terrain de squash': '',
    "Site d'aéromodélisme": '',
    'Salle de culturisme': '',
    'Aire de sports de glace sportive': '',
    'Salle de patinage sur roulette': '',
    "Parcours Acrobatique en Hauteur/Site d'accrobranche": '',
    'Bowling': '',
    'Salle ou terrain de badminton': '',
    'Salle ou terrain de jorkyball': '',
    "Piste d’aérodrome / d'aéroport": '',
    'Terrain de beach-volley': '',
    'Terrain de hockey sur gazon': '',
    'Salle de handball': '',
    "Aire d'atterrissage": '', 
    'Fosse à plongée': '',
    "Parcours d'initiation": '',
    "Salle d'haltérophilie": '',
    'Parcours 9 trous': '',
    'Terrain de baseball /softball': '', 
    'Fosse à plongeon': '',
    'Circuit de motocross': '',
    'Stade mixte': '', 
    'Courses sur piste': '',
    'Terrain de moto-ball': '',
    'Parcours 18 trous': '',
    'Salle ou terrain de paintball': '',
    'Terrain de boules traditionnelles': '',
    'Terrain de padel': '',
    'Mur ou fronton mixte': '',
    'Site de pêche': '',
    'Salle de spectacle / Zenith': '',
    'But/panier isolé de sport collectif': '',
    'Anneau / piste de cyclisme': '',
    'Practice': '',
    'Terrain de football américain': 'FootBall Américain',
    'Pas de tir aux plateaux': '',
    'Site de modélisme automobile': '',
    "Salle de blocs artificiels d'escalade": 'Escalade', 
    'Anneau de Roller': '',
    'Baignade aménagée': '',
    'Circuit de vitesse': '',
    'Salle de volley-ball': '',
    'Structure de tourisme équestre': ''
}