categories = {
    'Court de tennis' : 'Tennis', 
    'Terrain de basket-ball': 'BasketBall',
    'Bassin sportif de natation': 'Piscine', 
    'Salle de gymnastique sportive': 'Gymnase',
    "Structure Artificielle d'Escalade": 'Escalade',
    'Terrain de rugby': 'Rugby',
    "Pas de tir à l'arc": "Tir", 
    'Salle multisports (gymnase)': 'Gymnase',
    'Boucle de randonnée': '', 
    "Site de blocs d'escalade": 'Escalade',
    'Plateau EPS/Multisports/city-stades': '',
    'Terrain de boules': 'Pétanque',
    'Carrière': 'Equitation', 
    'Carrière de dressage/rond de longe': 'Equitation',
    'Terrain de football': 'FootBall',
    'Salles polyvalentes / des fêtes / non spécialisées': '',
    'Salle de tennis de table': 'Tennis de table', 
    "Piste d'athlétisme isolée": 'Athlétisme',
    'Stade d’athlétisme': 'Athlétisme',
    'Salle de cours collectifs': '',
    "Salle d'escrime": '',
    'Piste de kart': '',
    'Salle de musculation/cardiotraining': '',
    'Terrain de pétanque': 'Pétanque',
    "Dojo / Salle d'arts martiaux": 'Arts martiaux',
    'Parcours sportif/santé': '',
    'Stade de ski nautique': '',
    'Salle de danse': 'Danse',
    'Parcours fixe de course d’orientation': '',
    "Site d'escalade en falaise": 'Escalade',
    'Skate park': 'SkatePark',
    'Piste de bicross': '',
    'Manège': '', 
    'Terrain de handball': 'Handball',
    'Aire de saut': '', 
    'Mur de tennis': 'Tennis',
    'Salle de boxe': 'Arts martiaux', 
    'Pas de tir à la cible': 'Tir',
    'Terrain de volley-ball': 'VolleyBall',
    'Parcours de cross': '', 
    'Bassin ludique de natation': '',
    'Bassin mixte de natation': '', 
    'Terrain de soccer': 'FootBall', 
    'Salle de basket': 'BasketBall',
    "Site d'activités aquatiques et nautiques": '',
    'Aire de décollage': '',
    'Terrain mixte': '', 
    'Salle de billard': '',
    "Bassin d'exercices aquatiques": '',
    'Piste de course sur le plat': '',
    'Aire de lancer': 'Athlétisme', 
    'Salle de lutte': 'Arts martiaux',
    'Salle ou terrain de squash': 'Tennis',
    "Site d'aéromodélisme": 'Salle de sport',
    'Salle de culturisme': 'Salle de sport',
    'Aire de sports de glace sportive': '',
    'Salle de patinage sur roulette': 'SkatePark',
    "Parcours Acrobatique en Hauteur/Site d'accrobranche": 'Escalade',
    'Bowling': '',
    'Salle ou terrain de badminton': '',
    'Salle ou terrain de jorkyball': '',
    "Piste d’aérodrome / d'aéroport": '',
    'Terrain de beach-volley': 'VolleyBall',
    'Terrain de hockey sur gazon': '',
    'Salle de handball': 'Handball',
    "Aire d'atterrissage": '', 
    'Fosse à plongée': 'Piscine',
    "Parcours d'initiation": '',
    "Salle d'haltérophilie": 'Salle de sport',
    'Parcours 9 trous': '',
    'Terrain de baseball /softball': 'Baseball', 
    'Fosse à plongeon': 'Piscine',
    'Circuit de motocross': '',
    'Stade mixte': '', 
    'Courses sur piste': 'Athlétisme',
    'Terrain de moto-ball': '',
    'Parcours 18 trous': '',
    'Salle ou terrain de paintball': '',
    'Terrain de boules traditionnelles': 'Pétanque',
    'Terrain de padel': 'Tennis',
    'Mur ou fronton mixte': '',
    'Site de pêche': '',
    'Salle de spectacle / Zenith': '',
    'But/panier isolé de sport collectif': '',
    'Anneau / piste de cyclisme': '',
    'Practice': '',
    'Terrain de football américain': 'FootBall Américain',
    'Pas de tir aux plateaux': 'Tir',
    'Site de modélisme automobile': '',
    "Salle de blocs artificiels d'escalade": 'Escalade', 
    'Anneau de Roller': 'SkatePark',
    'Baignade aménagée': '',
    'Circuit de vitesse': '',
    'Salle de volley-ball': 'VolleyBall',
    'Structure de tourisme équestre': 'Equitation'
}