categories = {}

categories = {
    'Court de tennis' : 'Tennis', 
    'Terrain de basket-ball': 'BasketBall',
    'Bassin sportif de natation': 'Natation', 
    'Salle de gymnastique sportive': 'Gymnase',
    "Structure Artificielle d'Escalade": 'Escalade',
    'Terrain de rugby': 'Rugby',
    "Pas de tir à l'arc": "Tir", 
    'Salle multisports (gymnase)': 'Gymnase',
    'Boucle de randonnée': 'Course à pied', 
    "Site de blocs d'escalade": 'Escalade',
    'Plateau EPS/Multisports/city-stades': 'Autres',
    'Terrain de boules': 'Pétanque',
    'Carrière': 'Equitation', 
    'Carrière de dressage/rond de longe': 'Equitation',
    'Terrain de football': 'FootBall',
    'Salles polyvalentes / des fêtes / non spécialisées': 'Gymnase',
    'Salle de tennis de table': 'Tennis de table', 
    "Piste d'athlétisme isolée": 'Athlétisme',
    'Stade d’athlétisme': 'Athlétisme',
    'Salle de cours collectifs': 'Salle de sport',
    "Salle d'escrime": 'Autres',
    'Piste de kart': 'Autres',
    'Salle de musculation/cardiotraining': 'Salle de sport',
    'Terrain de pétanque': 'Pétanque',
    "Dojo / Salle d'arts martiaux": 'Arts martiaux',
    'Parcours sportif/santé': 'Course à pied',
    'Stade de ski nautique': 'Autres',
    'Salle de danse': 'Danse',
    'Parcours fixe de course d’orientation': 'Course à pied',
    "Site d'escalade en falaise": 'Escalade',
    'Skate park': 'SkatePark',
    'Piste de bicross': 'Cyclisme',
    'Manège': 'Autres', 
    'Terrain de handball': 'Handball',
    'Aire de saut': 'Athlétisme', 
    'Mur de tennis': 'Tennis',
    'Salle de boxe': 'Arts martiaux', 
    'Pas de tir à la cible': 'Tir',
    'Terrain de volley-ball': 'VolleyBall',
    'Parcours de cross': 'Course à pied', 
    'Bassin ludique de natation': 'Natation',
    'Bassin mixte de natation': 'Natation', 
    'Terrain de soccer': 'FootBall', 
    'Salle de basket': 'BasketBall',
    "Site d'activités aquatiques et nautiques": 'Autres',
    'Aire de décollage': 'Autres',
    'Terrain mixte': 'Autres', 
    'Salle de billard': 'Autres',
    "Bassin d'exercices aquatiques": 'Natation',
    'Piste de course sur le plat': 'Course à pied',
    'Aire de lancer': 'Athlétisme', 
    'Salle de lutte': 'Arts martiaux',
    'Salle ou terrain de squash': 'Tennis',
    "Site d'aéromodélisme": 'Salle de sport',
    'Salle de culturisme': 'Salle de sport',
    'Aire de sports de glace sportive': 'Autres',
    'Salle de patinage sur roulette': 'SkatePark',
    "Parcours Acrobatique en Hauteur/Site d'accrobranche": 'Escalade',
    'Bowling': 'Autres',
    'Salle ou terrain de badminton': 'Tennis',
    'Salle ou terrain de jorkyball': 'Tennis',
    "Piste d’aérodrome / d'aéroport": 'Autres',
    'Terrain de beach-volley': 'VolleyBall',
    'Terrain de hockey sur gazon': 'Autres',
    'Salle de handball': 'Handball',
    "Aire d'atterrissage": 'Autres', 
    'Fosse à plongée': 'Natation',
    "Parcours d'initiation": 'Autres',
    "Salle d'haltérophilie": 'Salle de sport',
    'Parcours 9 trous': 'Autres',
    'Terrain de baseball /softball': 'Baseball', 
    'Fosse à plongeon': 'Natation',
    'Circuit de motocross': 'Autres',
    'Stade mixte': 'Autres', 
    'Courses sur piste': 'Athlétisme',
    'Terrain de moto-ball': 'Autres',
    'Parcours 18 trous': 'Autres',
    'Salle ou terrain de paintball': 'Autres',
    'Terrain de boules traditionnelles': 'Pétanque',
    'Terrain de padel': 'Tennis',
    'Mur ou fronton mixte': 'Escalade',
    'Site de pêche': 'Autres',
    'Salle de spectacle / Zenith': 'Autres',
    'But/panier isolé de sport collectif': '?',
    'Anneau / piste de cyclisme': 'Cyclisme',
    'Practice': 'Autres',
    'Terrain de football américain': 'FootBall Américain',
    'Pas de tir aux plateaux': 'Tir',
    'Site de modélisme automobile': 'Autres',
    "Salle de blocs artificiels d'escalade": 'Escalade', 
    'Anneau de Roller': 'SkatePark',
    'Baignade aménagée': 'Natation',
    'Circuit de vitesse': 'Autres',
    'Salle de volley-ball': 'VolleyBall',
    'Structure de tourisme équestre': 'Equitation'
}
